name: polyellipsoid 
channels:
  - conda-forge
dependencies:
  - mbuild>=0.15
  - freud
  - gmso
  - gsd
  - hoomd=*=*cpu*
  - numpy
  - pip
  - pytest
  - pytest-cov
  - python
  - pip:
      - git+https://github.com/cmelab/cmeutils.git@master

